load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    vars X Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    eq signalAll(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : signal(T, T1), subprocesses : S, state : STATE > signalAll(PS, T1) .

    ceq signal(P T, T1) = P (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = P signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-call-activity-implicit-exclusive-and-parallel-gateway is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses
    vars P : Configuration . --- processes

    --- Generated rules
    rl [start_StartEvent_1] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("start (StartEvent_1)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("start_A (Flow_1lwnvn2)" T), subprocesses : (S), state : Running > .
    rl [A_Activity_1gofaru_start] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("start_A (Flow_1lwnvn2)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("A (Activity_1gofaru)" T), subprocesses : (S), state : Running > .
    rl [A_Activity_1gofaru_end] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("A (Activity_1gofaru)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("a2 (Flow_0mnkkon)" "a1 (Flow_0g9v3mg)" T), subprocesses : (S), state : Running > .
    rl [B_Activity_1cnewyu_Flow_08du15s_start] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("a3 (Flow_08du15s)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("B (Activity_1cnewyu)" T), subprocesses : (S), state : Running > .
    rl [B_Activity_1cnewyu_Flow_1tp5cpl_start] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("a4 (Flow_1tp5cpl)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("B (Activity_1cnewyu)" T), subprocesses : (S), state : Running > .
    rl [B_Activity_1cnewyu_end] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("B (Activity_1cnewyu)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("B_end (Flow_19r98jz)" T), subprocesses : (S), state : Running > .
    rl [end_Event_08ww8rq] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("B_end (Flow_19r98jz)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [Subprocess_Activity_08nz8l4_Flow_0mnkkon_start] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("a2 (Flow_0mnkkon)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : (T), subprocesses : (< "Subprocess" : ProcessSnapshot | tokens : ("start_sub (Event_0pov758)"), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess_Activity_08nz8l4_Flow_0g9v3mg_start] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("a1 (Flow_0g9v3mg)" T), subprocesses : (S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : (T), subprocesses : (< "Subprocess" : ProcessSnapshot | tokens : ("start_sub (Event_0pov758)"), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess_Activity_08nz8l4_end] :  < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : (T), subprocesses : (< "Subprocess" : ProcessSnapshot | tokens : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("a3 (Flow_08du15s)" "a4 (Flow_1tp5cpl)" T), subprocesses : (S), state : Running > .
    rl [start_sub_Event_0pov758] :  < "Subprocess" : ProcessSnapshot | tokens : ("start_sub (Event_0pov758)" T), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : ("start_sub_Subactivity (Flow_1963tcn)" T), subprocesses : (S), state : Running > .
    rl [Subactivity_Activity_023wdnt_start] :  < "Subprocess" : ProcessSnapshot | tokens : ("start_sub_Subactivity (Flow_1963tcn)" T), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : ("Subactivity (Activity_023wdnt)" T), subprocesses : (S), state : Running > .
    rl [Subactivity_Activity_023wdnt_end] :  < "Subprocess" : ProcessSnapshot | tokens : ("Subactivity (Activity_023wdnt)" T), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : ("Subactivity_end_sub (Flow_08jnebl)" T), subprocesses : (S), state : Running > .
    rl [end_sub_Event_0qra2k2] :  < "Subprocess" : ProcessSnapshot | tokens : ("Subactivity_end_sub (Flow_08jnebl)" T), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "call-activity-implicit-exclusive-and-parallel-gateway" : BPMNSystem | messages : (none), processes : (< "call-activity-implicit-exclusive-and-parallel-gateway" : ProcessSnapshot | tokens : ("start (StartEvent_1)"), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-call-activity-implicit-exclusive-and-parallel-gateway .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet .
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

red modelCheck(init,  <> [] allTerminated) .
