load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is
    pr STRING .
    pr NAT .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    var X : String .
    var Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .

    op size : MSet -> Nat .
    eq size(none) = 0 .
    eq size(X S) = size(S) + 1 .

    op lessOrEqualSize : MSet MSet -> Bool .
    ceq lessOrEqualSize(S, S1) = true if size(S) <= size(S1) .
    eq lessOrEqualSize(S, S1) = false [owise] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op signals :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    --- Auxiliary
    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    ceq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG signal(T, T1)), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) if lessOrEqualSize(SIG, T1). --- maximum signal bound is the number of tokens.
    eq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) [owise] .

    ceq signal(P T, T1) = (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, signals : SIG, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, signals : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-call-activity-complex is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T T1 : MSet . --- tokens
    vars SIG SIG1 : MSet . --- signals
    vars M : MSet . --- messages
    vars S1 S : Configuration . --- subprocesses
    vars P : Configuration . --- processes
    vars PS : Configuration . --- other processes

    --- Generated rules
    rl [A_Activity_09om2vm_start] :  < "p1" : ProcessSnapshot | tokens : ("start_p1_A (Flow_1tl2d3e)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("A (Activity_09om2vm)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [A_Activity_09om2vm_end] :  < "p1" : ProcessSnapshot | tokens : ("A (Activity_09om2vm)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("A_P1_Subprocess (Flow_0xs58is)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_p1_Event_0ayqkfq] :  < "p1" : ProcessSnapshot | tokens : ("P1_Subprocess_end_p1 (Flow_1lsia9d)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_p1_Event_0ge9b6d] :  < "p1" : ProcessSnapshot | tokens : ("start_p1 (Event_0ge9b6d)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start_p1_A (Flow_1tl2d3e)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [P1_Subprocess_Activity_0ryy3cp_start] :  < "p1" : ProcessSnapshot | tokens : ("A_P1_Subprocess (Flow_0xs58is)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "P1_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p1 (Event_1e18lzi)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [P1_Subprocess_Activity_0ryy3cp_end] :  < "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "P1_Subprocess" : ProcessSnapshot | tokens : (none), signals : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("P1_Subprocess_end_p1 (Flow_1lsia9d)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_sub_p1_Event_1e18lzi] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p1 (Event_1e18lzi)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p1_p1 (Flow_1bemas0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [p1_Gateway_13zypwp] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p1_p1 (Flow_1bemas0)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("p1_C1 (Flow_1uk7xtk)" "p1_C2 (Flow_0nea78g)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [C1_Activity_07x6xib_start] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("p1_C1 (Flow_1uk7xtk)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("C1 (Activity_07x6xib)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [C1_Activity_07x6xib_end] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("C1 (Activity_07x6xib)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("C1_p2 (Flow_0k4ys4o)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [C2_Activity_1nugyf2_start] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("p1_C2 (Flow_0nea78g)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("C2 (Activity_1nugyf2)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [C2_Activity_1nugyf2_end] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("C2 (Activity_1nugyf2)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("C2_p2 (Flow_0f9ur9m)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [p2_Gateway_0ibpt86] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("C1_p2 (Flow_0k4ys4o)" "C2_p2 (Flow_0f9ur9m)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("p2_start_p2 (Flow_0zy9s8q)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_p2_Event_0rudo08] :  < "p1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P1_Subprocess" : ProcessSnapshot | tokens : ("p2_start_p2 (Flow_0zy9s8q)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > => < "p1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P1_Subprocess" : ProcessSnapshot | tokens : ("start_p2_S1_catch (Flow_177pz9l)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > < "p2" : ProcessSnapshot | tokens : ("start_p2_P2_Subprocess (Flow_1v0hciw)"), signals : (none), subprocesses : (none), state : Running > .
    rl [S1_catch_Event_12opj9k] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("start_p2_S1_catch (Flow_177pz9l)" T), signals : ("start_p2_S1_catch (Flow_177pz9l)_signal" SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : ("S1_catch_message_throw (Flow_11aeugh)" T), signals : (SIG), subprocesses : (S), state : Running > .
    rl [message_throw_Event_0kjlxnm] :  < "call-activity-complex" : BPMNSystem | messages : (M), processes : (< "p1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P1_Subprocess" : ProcessSnapshot | tokens : ("S1_catch_message_throw (Flow_11aeugh)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "call-activity-complex" : BPMNSystem | messages : ("message_throw_message_catch (Flow_184jol3)" M), processes : (< "p1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P1_Subprocess" : ProcessSnapshot | tokens : ("message_throw_end_sub_p1 (Flow_0l7i58t)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [end_sub_p1_Event_16mo5pa] :  < "P1_Subprocess" : ProcessSnapshot | tokens : ("message_throw_end_sub_p1 (Flow_0l7i58t)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P1_Subprocess" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_p2_Event_0q39e1x] :  < "p2" : ProcessSnapshot | tokens : ("P2_Subprocess_end_p2 (Flow_01hejlw)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [P2_Subprocess_Activity_09eawur_start] :  < "p2" : ProcessSnapshot | tokens : ("start_p2_P2_Subprocess (Flow_1v0hciw)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "P2_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p2 (Event_1h5wmdo)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [P2_Subprocess_Activity_09eawur_end] :  < "p2" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "P2_Subprocess" : ProcessSnapshot | tokens : (none), signals : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("P2_Subprocess_end_p2 (Flow_01hejlw)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_sub_p2_Event_1h5wmdo] :  < "P2_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p2 (Event_1h5wmdo)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P2_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p2_S1_throw (Flow_052p2o6)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [message_catch_Event_0kjnu4e_start] :  < "P2_Subprocess" : ProcessSnapshot | tokens : ("S1_throw_message_catch (Flow_0m8wslc)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P2_Subprocess" : ProcessSnapshot | tokens : ("message_catch (Event_0kjnu4e)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [message_catch_Event_0kjnu4e] :  < "call-activity-complex" : BPMNSystem | messages : ("message_throw_message_catch (Flow_184jol3)" M), processes : (< "p2" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P2_Subprocess" : ProcessSnapshot | tokens : ("message_catch (Event_0kjnu4e)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "call-activity-complex" : BPMNSystem | messages : (M), processes : (< "p2" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P2_Subprocess" : ProcessSnapshot | tokens : ("message_catch_end_sub_p2 (Flow_05mx2n3)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [S1_throw_Event_0ad4evt] :  < "call-activity-complex" : BPMNSystem | messages : (M), processes : (< "p2" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P2_Subprocess" : ProcessSnapshot | tokens : ("start_sub_p2_S1_throw (Flow_052p2o6)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > PS) > => < "call-activity-complex" : BPMNSystem | messages : (M), processes : (signalAll(< "p2" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "P2_Subprocess" : ProcessSnapshot | tokens : ("S1_throw_message_catch (Flow_0m8wslc)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > PS, "start_p2_S1_catch (Flow_177pz9l)")) > .
    rl [end_sub_p2_Event_0j8c5tk] :  < "P2_Subprocess" : ProcessSnapshot | tokens : ("message_catch_end_sub_p2 (Flow_05mx2n3)" T), signals : (SIG), subprocesses : (S), state : Running > => < "P2_Subprocess" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "call-activity-complex" : BPMNSystem | messages : (none), processes : (< "p1" : ProcessSnapshot | tokens : ("start_p1 (Event_0ge9b6d)"), signals : (none), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-call-activity-complex .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet . --- tokens
    var SIG : MSet . --- signals
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), signals : SIG, subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

red modelCheck(init,  <> [] allTerminated) .
