load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    ops Running, Terminated : -> ProcessState [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .
    op ProcessSnapshot : -> Cid [ctor] .

    op terminate : Configuration -> Configuration .

    var P : String .
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    --- NOOP if none
    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, messages : M, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, messages : M, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, messages : M, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, messages : none, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, messages : M, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, messages : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-call-activity-no-start-event is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses

    --- Generated rules
    rl [start_Event_0ucjl4y] :  < "call-activity-no-start-event" : ProcessSnapshot | tokens : ("start (Event_0ucjl4y)" T), messages : (M), subprocesses : (S), state : Running > => < "call-activity-no-start-event" : ProcessSnapshot | tokens : ("start_Subprocess (Flow_1qfreid)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [Subprocess_Activity_1xp155m] :  < "call-activity-no-start-event" : ProcessSnapshot | tokens : ("start_Subprocess (Flow_1qfreid)" T), messages : (M), subprocesses : (S), state : Running > => < "call-activity-no-start-event" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (< "Subprocess" : ProcessSnapshot | tokens : ("A (Activity_0palugd)" "e1 (Gateway_1icv858)" "p1 (Gateway_1dk047s)"), messages : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess_Activity_1xp155m_end] :  < "call-activity-no-start-event" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (< "Subprocess" : ProcessSnapshot | tokens : (none), messages : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "call-activity-no-start-event" : ProcessSnapshot | tokens : ("Subprocess_end (Flow_1oeatxr)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [A_Activity_0palugd_end] :  < "Subprocess" : ProcessSnapshot | tokens : ("A (Activity_0palugd)" T), messages : (M), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : ("A_endA (Flow_020erk8)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [e1_Gateway_1icv858] :  < "Subprocess" : ProcessSnapshot | tokens : ("e1 (Gateway_1icv858)" T), messages : (M), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : ("e1_e1_end (Flow_1h7se5m)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [endA_Event_17dw7l3] :  < "Subprocess" : ProcessSnapshot | tokens : ("A_endA (Flow_020erk8)" T), messages : (M), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [e1_end_Event_0h7019h] :  < "Subprocess" : ProcessSnapshot | tokens : ("e1_e1_end (Flow_1h7se5m)" T), messages : (M), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [p1_end_Event_1iq0ir1] :  < "Subprocess" : ProcessSnapshot | tokens : ("p1_p1_end (Flow_09zx1yd)" T), messages : (M), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [p1_Gateway_1dk047s] :  < "Subprocess" : ProcessSnapshot | tokens : ("p1 (Gateway_1dk047s)" T), messages : (M), subprocesses : (S), state : Running > => < "Subprocess" : ProcessSnapshot | tokens : ("p1_p1_end (Flow_09zx1yd)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [end_Event_0catini] :  < "call-activity-no-start-event" : ProcessSnapshot | tokens : ("Subprocess_end (Flow_1oeatxr)" T), messages : (M), subprocesses : (S), state : Running > => < "call-activity-no-start-event" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "call-activity-no-start-event" : ProcessSnapshot | tokens : ("start (Event_0ucjl4y)"), messages : (none), subprocesses : (none), state : Running > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-call-activity-no-start-event .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X : Oid .
    var T : MSet .
    var M : MSet .
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : ProcessSnapshot | tokens : T, messages : M, subprocesses : S, state : Running > C |= allTerminated = false .
    eq C |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : ProcessSnapshot | tokens : (T1 T1 T), messages : M, subprocesses : S, state : State > C |= unsafe = true .
    eq C |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
