load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .

    ops Running, Terminated : -> ProcessState [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .
    op ProcessSnapshot : -> Cid [ctor] .
    subsort String < Oid .

    var P : String .

    rl [terminateProcess] :
    < P : ProcessSnapshot | tokens : none, messages : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, messages : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-exclusive-event-based-gateway is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T T1 : MSet . --- tokens
    vars M1 M : MSet . --- messages
    vars S1 S : Configuration . --- subprocesses

    --- Generated rules
    rl [start_p1_StartEvent_1] :  < "p1" : ProcessSnapshot | tokens : ("start_p1 (StartEvent_1)" T), messages : (M), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start_p1_eventG (Flow_0m6a8pc)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [eventG_Gateway_0xg98fy] :  < "p1" : ProcessSnapshot | tokens : ("start_p1_eventG (Flow_0m6a8pc)" T), messages : (M), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [end1_p1_Event_1udsije] :  < "p1" : ProcessSnapshot | tokens : ("r_msg1_end1_p1 (Flow_19bavl8)" T), messages : (M), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [r_msg1_Event_03mv4n4] :  < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T), messages : ("t_msg1_r_msg1" M), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("r_msg1_end1_p1 (Flow_19bavl8)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [end2_p1_Event_1wy5zfo] :  < "p1" : ProcessSnapshot | tokens : ("r_msg2_end2_p1 (Flow_03plkl9)" T), messages : (M), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [r_msg2_Activity_1up3t2i] :  < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T), messages : ("t_msg2_r_msg2" M), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("r_msg2_end2_p1 (Flow_03plkl9)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [start_p2_Event_08j4bud] :  < "p2" : ProcessSnapshot | tokens : ("start_p2 (Event_08j4bud)" T), messages : (M), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("start_p2_e1 (Flow_1w3o3v4)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [e1_Gateway_1i0mins] :  < "p2" : ProcessSnapshot | tokens : ("start_p2_e1 (Flow_1w3o3v4)" T), messages : (M), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("e1_t_msg1 (Flow_1ef2vkv)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [e1_Gateway_1i0mins] :  < "p2" : ProcessSnapshot | tokens : ("start_p2_e1 (Flow_1w3o3v4)" T), messages : (M), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("e1_t_msg2 (Flow_0te57tb)" T), messages : (M), subprocesses : (S), state : Running > .
    rl [end1_p2_Event_1dxc5mz] :  < "p2" : ProcessSnapshot | tokens : ("t_msg1_end1_p2 (Flow_1477wmb)" T), messages : (M), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [t_msg1_Event_120uhkz] :  < "p2" : ProcessSnapshot | tokens : ("e1_t_msg1 (Flow_1ef2vkv)" T), messages : (M), subprocesses : (S), state : Running > < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T1), messages : (M1), subprocesses : (S1), state : Running > => < "p2" : ProcessSnapshot | tokens : ("t_msg1_end1_p2 (Flow_1477wmb)" T), messages : (M), subprocesses : (S), state : Running > < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T1), messages : ("t_msg1_r_msg1" M1), subprocesses : (S1), state : Running > .
    rl [end2_p2_Event_0lg0bxg] :  < "p2" : ProcessSnapshot | tokens : ("t_msg2_end2_p2 (Flow_1fqp9d1)" T), messages : (M), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), messages : (M), subprocesses : (S), state : Running > .
    rl [t_msg2_Event_1fi0nvi] :  < "p2" : ProcessSnapshot | tokens : ("e1_t_msg2 (Flow_0te57tb)" T), messages : (M), subprocesses : (S), state : Running > < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T1), messages : (M1), subprocesses : (S1), state : Running > => < "p2" : ProcessSnapshot | tokens : ("t_msg2_end2_p2 (Flow_1fqp9d1)" T), messages : (M), subprocesses : (S), state : Running > < "p1" : ProcessSnapshot | tokens : ("eventG (Gateway_0xg98fy)" T1), messages : ("t_msg2_r_msg2" M1), subprocesses : (S1), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "p1" : ProcessSnapshot | tokens : ("start_p1 (StartEvent_1)"), messages : (none), subprocesses : (none), state : Running >
    < "p2" : ProcessSnapshot | tokens : ("start_p2 (Event_08j4bud)"), messages : (none), subprocesses : (none), state : Running > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-exclusive-event-based-gateway .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X : Oid .
    var T : MSet .
    var M : MSet .
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : ProcessSnapshot | tokens : T, messages : M, subprocesses : S, state : Running > C |= allTerminated = false .
    eq C |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : ProcessSnapshot | tokens : (T1 T1 T), messages : M, subprocesses : S, state : State > C |= unsafe = true .
    eq C |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
