load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- Processes
    ops Running, Terminated : -> ProcessState [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .
    op ProcessSnapshot : -> Cid [ctor] .

    --- Message holder
    op MessageHolder : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .

    op terminate : Configuration -> Configuration .

    vars P, P1 : String .
    vars T : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    --- NOOP if none
    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-link-event is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses

    --- Generated rules
    rl [Link1_Event_0eyvs9a] :  < "link-event" : ProcessSnapshot | tokens : ("Link1" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("Link1_p2 (Flow_1m1cy19)" T), subprocesses : (S), state : Running > .
    rl [Link2_Event_00x0hdz] :  < "link-event" : ProcessSnapshot | tokens : ("Link2" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("Link2_p2 (Flow_0eumlnw)" T), subprocesses : (S), state : Running > .
    rl [start_StartEvent_1] :  < "link-event" : ProcessSnapshot | tokens : ("start (StartEvent_1)" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("start_p1 (Flow_1fl0c6v)" T), subprocesses : (S), state : Running > .
    rl [p1_Gateway_0qx5e75] :  < "link-event" : ProcessSnapshot | tokens : ("start_p1 (Flow_1fl0c6v)" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("p1_Link1 (Flow_03y9o1z)" "p1_Link2 (Flow_0kxj4zu)" T), subprocesses : (S), state : Running > .
    rl [Link1_Event_0wqyqlc] :  < "link-event" : ProcessSnapshot | tokens : ("p1_Link1 (Flow_03y9o1z)" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("Link1" T), subprocesses : (S), state : Running > .
    rl [Link2_Event_05f4y5b] :  < "link-event" : ProcessSnapshot | tokens : ("p1_Link2 (Flow_0kxj4zu)" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("Link2" T), subprocesses : (S), state : Running > .
    rl [p2_Gateway_0bwp5hb] :  < "link-event" : ProcessSnapshot | tokens : ("Link1_p2 (Flow_1m1cy19)" "Link2_p2 (Flow_0eumlnw)" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : ("p2_end (Flow_0vgr37e)" T), subprocesses : (S), state : Running > .
    rl [end_Event_0q8vo7d] :  < "link-event" : ProcessSnapshot | tokens : ("p2_end (Flow_0vgr37e)" T), subprocesses : (S), state : Running > => < "link-event" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "messages" : MessageHolder | messages : (none) >
    < "link-event" : ProcessSnapshot | tokens : ("start (StartEvent_1)"), subprocesses : (none), state : Running > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-link-event .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X : Oid .
    var T : MSet .
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C |= allTerminated = false .
    eq C |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C |= unsafe = true .
    eq C |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
