load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is
    pr STRING .
    pr NAT .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    var X : String .
    var Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .

    op size : MSet -> Nat .
    eq size(none) = 0 .
    eq size(X S) = size(S) + 1 .

    op lessOrEqualSize : MSet MSet -> Bool .
    ceq lessOrEqualSize(S, S1) = true if size(S) <= size(S1) .
    eq lessOrEqualSize(S, S1) = false [owise] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op name :_ : String -> Attribute [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op signals :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    --- Auxiliary
    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    var X : Oid .
    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    ceq signalAll(< X : ProcessSnapshot | name : P, tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < X : ProcessSnapshot | name : P, tokens : T, signals : (SIG signal(T, T1)), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) if lessOrEqualSize(SIG, T1). --- maximum signal bound is the number of tokens.
    eq signalAll(< X : ProcessSnapshot | name : P, tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < X : ProcessSnapshot | name : P, tokens : T, signals : (SIG), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) [owise] .

    ceq signal(P T, T1) = (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< X : ProcessSnapshot | name : P, tokens : T, signals : SIG, subprocesses : S, state : Terminated >) = < X : ProcessSnapshot | name : P, tokens : T, signals : SIG, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< X : ProcessSnapshot | name : P, tokens : T, signals : SIG, subprocesses : S, state : STATE > PS) = < X : ProcessSnapshot | name : P, tokens : T, signals : SIG, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < X : ProcessSnapshot | name : P, tokens : none, signals : SIG, subprocesses : none, state : Running >
                            =>
    < X : ProcessSnapshot | name : P, tokens : none, signals : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-link-event is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars o0 : Oid . --- Oids
    vars T : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses
    vars P : Configuration . --- processes

    --- Generated rules
    rl [p1_pg1_Gateway_0qx5e75] :  < o0 : ProcessSnapshot | name : "p1", tokens : ("start_p1 -> p1_pg1 (Flow_1fl0c6v)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p1", tokens : ("p1_pg1 -> Link1 (Flow_03y9o1z)" "p1_pg1 -> Link2 (Flow_0kxj4zu)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Link1_Event_0wqyqlc] :  < o0 : ProcessSnapshot | name : "p1", tokens : ("p1_pg1 -> Link1 (Flow_03y9o1z)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p1", tokens : ("Link1 -> p1_pg2 (Flow_1m1cy19)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Link2_Event_05f4y5b] :  < o0 : ProcessSnapshot | name : "p1", tokens : ("p1_pg1 -> Link2 (Flow_0kxj4zu)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p1", tokens : ("Link2 -> p1_pg2 (Flow_0eumlnw)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [p1_pg2_Gateway_0bwp5hb] :  < o0 : ProcessSnapshot | name : "p1", tokens : ("Link1 -> p1_pg2 (Flow_1m1cy19)" "Link2 -> p1_pg2 (Flow_0eumlnw)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p1", tokens : ("p1_pg2 -> end_p1 (Flow_0vgr37e)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_p1_Event_0q8vo7d] :  < o0 : ProcessSnapshot | name : "p1", tokens : ("p1_pg2 -> end_p1 (Flow_0vgr37e)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p1", tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [p2_pg1_Gateway_1soqpw4] :  < o0 : ProcessSnapshot | name : "p2", tokens : ("start_p2 -> p2_pg1 (Flow_1pptdul)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p2", tokens : ("p2_pg1 -> Link1 (Flow_0lfpdhx)" "p2_pg1 -> Link2 (Flow_0ffqovc)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Link1_Event_1w81q7o] :  < o0 : ProcessSnapshot | name : "p2", tokens : ("p2_pg1 -> Link1 (Flow_0lfpdhx)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p2", tokens : ("Link1 -> p2_pg2 (Flow_0yi349b)" "Link1 -> p2_pg2 (Flow_0z8awck)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [p2_pg2_Gateway_12jffsl] :  < o0 : ProcessSnapshot | name : "p2", tokens : ("Link1 -> p2_pg2 (Flow_0yi349b)" "Link2 -> p2_pg2 (Flow_0l2nycr)" "Link1 -> p2_pg2 (Flow_0z8awck)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p2", tokens : ("p2_pg2 -> end_p2 (Flow_1gudwyv)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_p2_Event_15h4vpg] :  < o0 : ProcessSnapshot | name : "p2", tokens : ("p2_pg2 -> end_p2 (Flow_1gudwyv)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p2", tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [Link2_Event_1caprm2] :  < o0 : ProcessSnapshot | name : "p2", tokens : ("p2_pg1 -> Link2 (Flow_0ffqovc)" T), signals : (SIG), subprocesses : (S), state : Running > => < o0 : ProcessSnapshot | name : "p2", tokens : ("Link2 -> p2_pg2 (Flow_0l2nycr)" T), signals : (none), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "link-event" : BPMNSystem | messages : (none), processes : (< "0" : ProcessSnapshot | name : "p1", tokens : ("start_p1 -> p1_pg1 (Flow_1fl0c6v)"), signals : (none), subprocesses : (none), state : Running >
    < "1" : ProcessSnapshot | name : "p2", tokens : ("start_p2 -> p2_pg1 (Flow_1pptdul)"), signals : (none), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-link-event .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var N : String . --- name
    var T : MSet . --- tokens
    var SIG : MSet . --- signals
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | name : N, tokens : T, signals : SIG, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | name : N, tokens : (T1 T1 T), signals : SIG, subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

red modelCheck(init,  <> [] allTerminated) .
