load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- Processes
    ops Running, Terminated : -> ProcessState [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .
    op ProcessSnapshot : -> Cid [ctor] .

    --- Message holder
    op MessageHolder : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .

    op terminate : Configuration -> Configuration .

    vars P, P1 : String .
    vars T : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    --- NOOP if none
    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-multiple-start-events is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses

    --- Generated rules
    rl [start1_p1_StartEvent_1] :  < "p1" : ProcessSnapshot | tokens : ("start1_p1 (StartEvent_1)" T), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start1_p1_p_p1 (Flow_1p3gdcm)" T), subprocesses : (S), state : Running > .
    rl [start2_p1_Event_1avhncp] :  < "p1" : ProcessSnapshot | tokens : ("start2_p1 (Event_1avhncp)" T), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start2_p1_p_p1 (Flow_1bwtd34)" T), subprocesses : (S), state : Running > .
    rl [p_p1_Gateway_0djwvv3] :  < "p1" : ProcessSnapshot | tokens : ("start2_p1_p_p1 (Flow_1bwtd34)" "start1_p1_p_p1 (Flow_1p3gdcm)" T), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("p_p1_end_p1 (Flow_1hji70l)" T), subprocesses : (S), state : Running > .
    rl [end_p1_Event_0i28wix] :  < "p1" : ProcessSnapshot | tokens : ("p_p1_end_p1 (Flow_1hji70l)" T), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [start1_p2_Event_0rbdq43] :  < "p2" : ProcessSnapshot | tokens : ("start1_p2 (Event_0rbdq43)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("start1_p2_p_p2 (Flow_120g9dm)" T), subprocesses : (S), state : Running > .
    rl [start2_p2_Event_0rt8j9k] :  < "p2" : ProcessSnapshot | tokens : ("start2_p2 (Event_0rt8j9k)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("start2_p2_p_p2 (Flow_1f9dgmw)" T), subprocesses : (S), state : Running > .
    rl [p_p2_Gateway_09ghyqt] :  < "p2" : ProcessSnapshot | tokens : ("start2_p2_p_p2 (Flow_1f9dgmw)" "start1_p2_p_p2 (Flow_120g9dm)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("p_p2_end_p2 (Flow_17dpz8t)" T), subprocesses : (S), state : Running > .
    rl [end_p2_Event_1hg9h1w] :  < "p2" : ProcessSnapshot | tokens : ("p_p2_end_p2 (Flow_17dpz8t)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "messages" : MessageHolder | messages : (none) >
    < "p1" : ProcessSnapshot | tokens : ("start1_p1 (StartEvent_1)" "start2_p1 (Event_1avhncp)"), subprocesses : (none), state : Running >
    < "p2" : ProcessSnapshot | tokens : ("start1_p2 (Event_0rbdq43)" "start2_p2 (Event_0rt8j9k)"), subprocesses : (none), state : Running > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-multiple-start-events .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X : Oid .
    var T : MSet .
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C |= allTerminated = false .
    eq C |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C |= unsafe = true .
    eq C |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
