load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    vars X Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op signals :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    --- Auxiliary
    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    eq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG signal(T, T1)), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) .

    ceq signal(P T, T1) = (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, signals : SIG, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, signals : SIG, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-parallel-gateway is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses
    vars P : Configuration . --- processes

    --- Generated rules
    rl [start_StartEvent_1] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("start (StartEvent_1)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("start_a0 (Flow_1qxu4uv)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a0_Activity_029uqdv_start] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("start_a0 (Flow_1qxu4uv)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a0 (Activity_029uqdv)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a0_Activity_029uqdv_end] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a0 (Activity_029uqdv)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a0_a1 (Flow_0cg7cqo)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a1_Activity_194ixr2_start] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a0_a1 (Flow_0cg7cqo)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a1 (Activity_194ixr2)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a1_Activity_194ixr2_end] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a1 (Activity_194ixr2)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a1_p1 (Flow_1pf5izs)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [p1_Gateway_0a08dmu] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a1_p1 (Flow_1pf5izs)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("p1_a2_1 (Flow_06uejek)" "p1_a2_2 (Flow_1id82hx)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a2_1_Activity_1hsp815_start] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("p1_a2_1 (Flow_06uejek)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_1 (Activity_1hsp815)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a2_1_Activity_1hsp815_end] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_1 (Activity_1hsp815)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_1_p2 (Flow_1qlsryz)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [p2_Gateway_1t9ovia] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_1_p2 (Flow_1qlsryz)" "a2_2_p2 (Flow_1y8u2ok)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("p2_a3 (Flow_0rj1gn8)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a3_Activity_0mczhuc_start] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("p2_a3 (Flow_0rj1gn8)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a3 (Activity_0mczhuc)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a3_Activity_0mczhuc_end] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a3 (Activity_0mczhuc)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a3_end (Flow_1rdqmbz)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_Event_0sx78s8] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a3_end (Flow_1rdqmbz)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [a2_2_Activity_0v43tih_start] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("p1_a2_2 (Flow_1id82hx)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_2 (Activity_0v43tih)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [a2_2_Activity_0v43tih_end] :  < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_2 (Activity_0v43tih)" T), signals : (SIG), subprocesses : (S), state : Running > => < "parallel-gateway" : ProcessSnapshot | tokens : ("a2_2_p2 (Flow_1y8u2ok)" T), signals : (none), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "parallel-gateway" : BPMNSystem | messages : (none), processes : (< "parallel-gateway" : ProcessSnapshot | tokens : ("start (StartEvent_1)"), signals : (none), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-parallel-gateway .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet . --- tokens
    var SIG : MSet . --- signals
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), signals : SIG, subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

red modelCheck(init,  <> [] allTerminated) .
