load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is
    pr STRING .
    pr NAT .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    var X : String .
    var Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .

    op size : MSet -> Nat .
    eq size(none) = 0 .
    eq size(X S) = size(S) + 1 .

    op lessOrEqualSize : MSet MSet -> Bool .
    ceq lessOrEqualSize(S, S1) = true if size(S) <= size(S1) .
    eq lessOrEqualSize(S, S1) = false [owise] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op signals :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    --- Auxiliary
    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    ceq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG signal(T, T1)), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) if lessOrEqualSize(SIG, T1). --- maximum signal bound is the number of tokens.
    eq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) [owise] .

    ceq signal(P T, T1) = (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, signals : SIG, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, signals : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-subprocess-interrupting-boundary-events is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T T1 : MSet . --- tokens
    vars SIG SIG1 : MSet . --- signals
    vars M : MSet . --- messages
    vars S1 S S2 : Configuration . --- subprocesses
    vars P : Configuration . --- processes
    vars PS : Configuration . --- other processes

    --- Generated rules
    rl [start_StartEvent_1] :  < "p1" : ProcessSnapshot | tokens : ("start (StartEvent_1)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start_Subprocess1 (Flow_114zxb5)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Subprocess1_Activity_0zu4scn_start] :  < "p1" : ProcessSnapshot | tokens : ("start_Subprocess1 (Flow_114zxb5)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Subprocess1" : ProcessSnapshot | tokens : ("start_sub1 (Event_0mt4q3x)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess1_Activity_0zu4scn_end] :  < "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Subprocess1" : ProcessSnapshot | tokens : (none), signals : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("Subprocess1_Subprocess2 (Flow_0oh2vh6)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_sub1_Event_0mt4q3x] :  < "Subprocess1" : ProcessSnapshot | tokens : ("start_sub1 (Event_0mt4q3x)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Subprocess1" : ProcessSnapshot | tokens : ("start_sub1_end_sub1 (Flow_1uendr0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_sub1_Event_1jup1bz] :  < "Subprocess1" : ProcessSnapshot | tokens : ("start_sub1_end_sub1 (Flow_1uendr0)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Subprocess1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [none_Event_1pwtnqh] :  < "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Subprocess1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (S1), state : Running > S2), state : Running > => < "p1" : ProcessSnapshot | tokens : ("none_Subprocess2 (Flow_1x3jtgj)" T), signals : (none), subprocesses : (S2), state : Running > .
    rl [timer_Event_0jlum9m] :  < "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Subprocess1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (S1), state : Running > S2), state : Running > => < "p1" : ProcessSnapshot | tokens : ("timer_Subprocess2 (Flow_07bli59)" T), signals : (none), subprocesses : (S2), state : Running > .
    rl [Subprocess2_Activity_0iqgw9l_Flow_0oh2vh6_start] :  < "p1" : ProcessSnapshot | tokens : ("Subprocess1_Subprocess2 (Flow_0oh2vh6)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Subprocess2" : ProcessSnapshot | tokens : ("start_sub2 (Event_1jyq774)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess2_Activity_0iqgw9l_Flow_07bli59_start] :  < "p1" : ProcessSnapshot | tokens : ("timer_Subprocess2 (Flow_07bli59)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Subprocess2" : ProcessSnapshot | tokens : ("start_sub2 (Event_1jyq774)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess2_Activity_0iqgw9l_Flow_1x3jtgj_start] :  < "p1" : ProcessSnapshot | tokens : ("none_Subprocess2 (Flow_1x3jtgj)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Subprocess2" : ProcessSnapshot | tokens : ("start_sub2 (Event_1jyq774)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess2_Activity_0iqgw9l_end] :  < "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Subprocess2" : ProcessSnapshot | tokens : (none), signals : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("Subprocess2_Subprocess3 (Flow_13jkgk6)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_sub2_Event_1jyq774] :  < "Subprocess2" : ProcessSnapshot | tokens : ("start_sub2 (Event_1jyq774)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Subprocess2" : ProcessSnapshot | tokens : ("start_sub2_end_sub2 (Flow_153aslt)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_sub2_Event_1maioig] :  < "Subprocess2" : ProcessSnapshot | tokens : ("start_sub2_end_sub2 (Flow_153aslt)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Subprocess2" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [message_Event_0izwujm] :  < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : ("interruptMessage_message (Flow_0a1uc8s)" M), processes : (< "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Subprocess2" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (S1), state : Running > S2), state : Running > P) > => < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : (M), processes : (< "p1" : ProcessSnapshot | tokens : ("message_Subprocess3 (Flow_1wqrelp)" T), signals : (none), subprocesses : (S2), state : Running > P) > .
    rl [Subprocess3_Activity_1v2ytch_Flow_13jkgk6_start] :  < "p1" : ProcessSnapshot | tokens : ("Subprocess2_Subprocess3 (Flow_13jkgk6)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Subprocess3" : ProcessSnapshot | tokens : ("start_sub3 (Event_1agvno8)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess3_Activity_1v2ytch_Flow_1wqrelp_start] :  < "p1" : ProcessSnapshot | tokens : ("message_Subprocess3 (Flow_1wqrelp)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Subprocess3" : ProcessSnapshot | tokens : ("start_sub3 (Event_1agvno8)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Subprocess3_Activity_1v2ytch_end] :  < "p1" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Subprocess3" : ProcessSnapshot | tokens : (none), signals : (none), subprocesses : (none), state : Terminated > S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("Subprocess3_end (Flow_0uhx7oz)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_sub3_Event_1agvno8] :  < "Subprocess3" : ProcessSnapshot | tokens : ("start_sub3 (Event_1agvno8)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Subprocess3" : ProcessSnapshot | tokens : ("start_sub3_end_sub3 (Flow_1q5pw23)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_sub3_Event_0eflm1o] :  < "Subprocess3" : ProcessSnapshot | tokens : ("start_sub3_end_sub3 (Flow_1q5pw23)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Subprocess3" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [end_Event_0a5btx4] :  < "p1" : ProcessSnapshot | tokens : ("Subprocess3_end (Flow_0uhx7oz)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [signal_end_Event_116g6wp] :  < "p1" : ProcessSnapshot | tokens : ("signal_signal_end (Flow_1m0lzvc)" T), signals : (SIG), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [start_trigger_Event_0ud5o1c] :  < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger (Event_0ud5o1c)" T), signals : (SIG), subprocesses : (S), state : Running > => < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger_interruptMessage (Flow_0u2o9mg)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [interruptMessage_Event_0ajr2wq] :  < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : (M), processes : (< "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger_interruptMessage (Flow_0u2o9mg)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : ("interruptMessage_message (Flow_0a1uc8s)" M), processes : (< "interruptTrigger" : ProcessSnapshot | tokens : ("interruptMessage_interruptSignal (Flow_18eds9w)" T), signals : (SIG), subprocesses : (S), state : Running > P) > .
    rl [interruptSignal_Event_1p4o1ul] :  < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : (M), processes : (< "interruptTrigger" : ProcessSnapshot | tokens : ("interruptMessage_interruptSignal (Flow_18eds9w)" T), signals : (SIG), subprocesses : (S), state : Running > PS) > => < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : (M), processes : (signalAll(< "interruptTrigger" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (S), state : Running > PS, "Subprocess3 (Activity_1v2ytch)")) > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "subprocess-interrupting-boundary-events" : BPMNSystem | messages : (none), processes : (< "p1" : ProcessSnapshot | tokens : ("start (StartEvent_1)"), signals : (none), subprocesses : (none), state : Running >
    < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger (Event_0ud5o1c)"), signals : (none), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-subprocess-interrupting-boundary-events .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet . --- tokens
    var SIG : MSet . --- signals
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), signals : SIG, subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

red modelCheck(init,  <> [] allTerminated) .
