load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- Processes
    ops Running, Terminated : -> ProcessState [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .
    op ProcessSnapshot : -> Cid [ctor] .

    --- Message holder
    op MessageHolder : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .

    op terminate : Configuration -> Configuration .

    vars P, P1 : String .
    vars T : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    --- NOOP if none
    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-task-interrupting-boundary-events is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses

    --- Generated rules
    rl [start_StartEvent_1] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("start (StartEvent_1)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : ("start_Task (Flow_1f4z70z)" T), subprocesses : (S), state : Running > .
    rl [Task_Activity_0l12w7i_start] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("start_Task (Flow_1f4z70z)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : ("Task (Activity_0l12w7i)" T), subprocesses : (S), state : Running > .
    rl [Task_Activity_0l12w7i_end] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("Task (Activity_0l12w7i)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : ("Task_end (Flow_1a9xer8)" T), subprocesses : (S), state : Running > .
    rl [n1_Event_0f3lbm7] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("Task (Activity_0l12w7i)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : ("n1_n1_end (Flow_1h5llv5)" T), subprocesses : (S), state : Running > .
    rl [m1_Event_0bz0xda] :  < "messages" : MessageHolder | messages : ("interruptMessage_m1" M) > < "Activity boundary events" : ProcessSnapshot | tokens : ("Task (Activity_0l12w7i)" T), subprocesses : (S), state : Running > => < "messages" : MessageHolder | messages : (M) > < "Activity boundary events" : ProcessSnapshot | tokens : ("m1_m1_end (Flow_0y1lybr)" T), subprocesses : (S), state : Running > .
    rl [t1_Event_0h1b9o9] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("Task (Activity_0l12w7i)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : ("t1_t1_end (Flow_1jzbhgq)" T), subprocesses : (S), state : Running > .
    rl [m1_end_Event_0nkgghw] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("m1_m1_end (Flow_0y1lybr)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [t1_end_Event_0idbvoc] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("t1_t1_end (Flow_1jzbhgq)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [n1_end_Event_0xrgzcz] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("n1_n1_end (Flow_1h5llv5)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [end_Event_0437i58] :  < "Activity boundary events" : ProcessSnapshot | tokens : ("Task_end (Flow_1a9xer8)" T), subprocesses : (S), state : Running > => < "Activity boundary events" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [start_trigger_Event_0lb8a5z] :  < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger (Event_0lb8a5z)" T), subprocesses : (S), state : Running > => < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger_signalOrMessage (Flow_0kk10m4)" T), subprocesses : (S), state : Running > .
    rl [signalOrMessage_Gateway_0wxegd1] :  < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger_signalOrMessage (Flow_0kk10m4)" T), subprocesses : (S), state : Running > => < "interruptTrigger" : ProcessSnapshot | tokens : ("signalOrMessage_interruptMessage (Flow_0uvbzn4)" T), subprocesses : (S), state : Running > .
    rl [interruptMessage_Event_0kfz6j8] :  < "interruptTrigger" : ProcessSnapshot | tokens : ("signalOrMessage_interruptMessage (Flow_0uvbzn4)" T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : (M) > => < "interruptTrigger" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : ("interruptMessage_m1" M) > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "messages" : MessageHolder | messages : (none) >
    < "Activity boundary events" : ProcessSnapshot | tokens : ("start (StartEvent_1)"), subprocesses : (none), state : Running >
    < "interruptTrigger" : ProcessSnapshot | tokens : ("start_trigger (Event_0lb8a5z)"), subprocesses : (none), state : Running > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-task-interrupting-boundary-events .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X : Oid .
    var T : MSet .
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C |= allTerminated = false .
    eq C |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C |= unsafe = true .
    eq C |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
