load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    op terminate : Configuration -> Configuration .
    --- Replace all occurrences of the first object with the second object in the given configuration.
    op forAll : Configuration Object Object -> Configuration .

    vars P P1 : String .
    vars T : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    vars o1 o2 o3 : Object .
    eq forAll(none, o2, o3) = none .
    --- Replace the occurrence of o2 by o3
    eq forAll(o2 PS, o2, o3) = forAll(o3 PS, o2, o3) .
    --- Ignore o1 since it is not the same as o2.
    ceq forAll(o1 PS, o2, o3) = o1 forAll(PS, o2, o3) if o1 =/= o2 .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-terminate-end-event is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses
    vars P : Configuration . --- processes

    --- Generated rules
    rl [start_StartEvent_1] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("start (StartEvent_1)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : ("start_p1 (Flow_0smgvfd)" T), subprocesses : (S), state : Running > .
    rl [p1_Gateway_03pfysn] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("start_p1 (Flow_0smgvfd)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : ("p1_A (Flow_01ts0by)" "p1_B (Flow_0p8b824)" T), subprocesses : (S), state : Running > .
    rl [A_Activity_19fz4g9_start] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("p1_A (Flow_01ts0by)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : ("A (Activity_19fz4g9)" T), subprocesses : (S), state : Running > .
    rl [A_Activity_19fz4g9_end] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("A (Activity_19fz4g9)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : ("A_end (Flow_0zgj5gw)" T), subprocesses : (S), state : Running > .
    rl [B_Activity_1ol0d86_start] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("p1_B (Flow_0p8b824)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : ("B (Activity_1ol0d86)" T), subprocesses : (S), state : Running > .
    rl [B_Activity_1ol0d86_end] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("B (Activity_1ol0d86)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : ("B_terminate_end (Flow_178sut1)" T), subprocesses : (S), state : Running > .
    rl [terminate_end_Event_0i6p82s] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("B_terminate_end (Flow_178sut1)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : (T), subprocesses : (terminate(S)), state : Terminated > .
    rl [end_Event_1bkqcvd] :  < "terminate-end-event" : ProcessSnapshot | tokens : ("A_end (Flow_0zgj5gw)" T), subprocesses : (S), state : Running > => < "terminate-end-event" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "terminate-end-event" : BPMNSystem | messages : (none), processes : (< "terminate-end-event" : ProcessSnapshot | tokens : ("start (StartEvent_1)"), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-terminate-end-event .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet .
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
