load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- Processes
    ops Running, Terminated : -> ProcessState [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .
    op ProcessSnapshot : -> Cid [ctor] .

    --- Message holder
    op MessageHolder : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .

    op terminate : Configuration -> Configuration .

    vars P, P1 : String .
    vars T : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    --- NOOP if none
    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-two-incoming-message-flows-receive-task is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses

    --- Generated rules
    rl [start_p2_Event_1g2ic8d] :  < "p2" : ProcessSnapshot | tokens : ("start_p2 (Event_1g2ic8d)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("start_p2_Receive (Flow_042vupp)" T), subprocesses : (S), state : Running > .
    rl [end_p2_Event_0mgavn2] :  < "p2" : ProcessSnapshot | tokens : ("Receive_end_p2 (Flow_12j91j4)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [Receive_Activity_0pgd8ed_start] :  < "p2" : ProcessSnapshot | tokens : ("start_p2_Receive (Flow_042vupp)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("Receive (Activity_0pgd8ed)" T), subprocesses : (S), state : Running > .
    rl [Receive_Activity_0pgd8ed_end] :  < "p2" : ProcessSnapshot | tokens : ("Receive (Activity_0pgd8ed)" T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : ("end_p2_Receive" M) > => < "messages" : MessageHolder | messages : (M) > < "p2" : ProcessSnapshot | tokens : ("Receive_end_p2 (Flow_12j91j4)" T), subprocesses : (S), state : Running > .
    rl [Receive_Activity_0pgd8ed_end] :  < "p2" : ProcessSnapshot | tokens : ("Receive (Activity_0pgd8ed)" T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : ("end_p1_Receive" M) > => < "messages" : MessageHolder | messages : (M) > < "p2" : ProcessSnapshot | tokens : ("Receive_end_p2 (Flow_12j91j4)" T), subprocesses : (S), state : Running > .
    rl [end_p2_Event_0n0galh] :  < "p3" : ProcessSnapshot | tokens : ("start_p3_end_p2 (Flow_16u01g7)" T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : (M) > => < "p3" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : ("end_p2_Receive" M) > .
    rl [start_p3_Event_0bhy3w7] :  < "p3" : ProcessSnapshot | tokens : ("start_p3 (Event_0bhy3w7)" T), subprocesses : (S), state : Running > => < "p3" : ProcessSnapshot | tokens : ("start_p3_end_p2 (Flow_16u01g7)" T), subprocesses : (S), state : Running > .
    rl [end_p1_Event_1xbunmt] :  < "p1" : ProcessSnapshot | tokens : ("start_p1_end_p1 (Flow_1ttcsey)" T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : (M) > => < "p1" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > < "messages" : MessageHolder | messages : ("end_p1_Receive" M) > .
    rl [start_p1_Event_1hsgsto] :  < "p1" : ProcessSnapshot | tokens : ("start_p1 (Event_1hsgsto)" T), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start_p1_end_p1 (Flow_1ttcsey)" T), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "messages" : MessageHolder | messages : (none) >
    < "p2" : ProcessSnapshot | tokens : ("start_p2 (Event_1g2ic8d)"), subprocesses : (none), state : Running >
    < "p3" : ProcessSnapshot | tokens : ("start_p3 (Event_0bhy3w7)"), subprocesses : (none), state : Running >
    < "p1" : ProcessSnapshot | tokens : ("start_p1 (Event_1hsgsto)"), subprocesses : (none), state : Running > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-two-incoming-message-flows-receive-task .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X : Oid .
    var T : MSet .
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C |= allTerminated = false .
    eq C |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C |= unsafe = true .
    eq C |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .
endm

red modelCheck(init,  <> [] allTerminated) .
