load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is pr
    STRING .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    vars X Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    eq signalAll(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : signal(T, T1), subprocesses : S, state : STATE > signalAll(PS, T1) .

    ceq signal(P T, T1) = P (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = P signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-two-incoming-message-flows-receive-task is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T : MSet . --- tokens
    vars M : MSet . --- messages
    vars S : Configuration . --- subprocesses
    vars P : Configuration . --- processes

    --- Generated rules
    rl [start_p2_Event_1g2ic8d] :  < "p2" : ProcessSnapshot | tokens : ("start_p2 (Event_1g2ic8d)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("start_p2_Receive (Flow_042vupp)" T), subprocesses : (S), state : Running > .
    rl [end_p2_Event_0mgavn2] :  < "p2" : ProcessSnapshot | tokens : ("Receive_end_p2 (Flow_12j91j4)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > .
    rl [Receive_Activity_0pgd8ed_start] :  < "p2" : ProcessSnapshot | tokens : ("start_p2_Receive (Flow_042vupp)" T), subprocesses : (S), state : Running > => < "p2" : ProcessSnapshot | tokens : ("Receive (Activity_0pgd8ed)" T), subprocesses : (S), state : Running > .
    rl [Receive_Activity_0pgd8ed_end] :  < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : ("end_p2_Receive" M), processes : (< "p2" : ProcessSnapshot | tokens : ("Receive (Activity_0pgd8ed)" T), subprocesses : (S), state : Running > P) > => < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : (M), processes : (< "p2" : ProcessSnapshot | tokens : ("Receive_end_p2 (Flow_12j91j4)" T), subprocesses : (S), state : Running > P) > .
    rl [Receive_Activity_0pgd8ed_end] :  < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : ("end_p1_Receive" M), processes : (< "p2" : ProcessSnapshot | tokens : ("Receive (Activity_0pgd8ed)" T), subprocesses : (S), state : Running > P) > => < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : (M), processes : (< "p2" : ProcessSnapshot | tokens : ("Receive_end_p2 (Flow_12j91j4)" T), subprocesses : (S), state : Running > P) > .
    rl [end_p2_Event_0n0galh] :  < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : (M), processes : (< "p3" : ProcessSnapshot | tokens : ("start_p3_end_p2 (Flow_16u01g7)" T), subprocesses : (S), state : Running > P) > => < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : ("end_p2_Receive" M), processes : (< "p3" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > P) > .
    rl [start_p3_Event_0bhy3w7] :  < "p3" : ProcessSnapshot | tokens : ("start_p3 (Event_0bhy3w7)" T), subprocesses : (S), state : Running > => < "p3" : ProcessSnapshot | tokens : ("start_p3_end_p2 (Flow_16u01g7)" T), subprocesses : (S), state : Running > .
    rl [end_p1_Event_1xbunmt] :  < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : (M), processes : (< "p1" : ProcessSnapshot | tokens : ("start_p1_end_p1 (Flow_1ttcsey)" T), subprocesses : (S), state : Running > P) > => < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : ("end_p1_Receive" M), processes : (< "p1" : ProcessSnapshot | tokens : (T), subprocesses : (S), state : Running > P) > .
    rl [start_p1_Event_1hsgsto] :  < "p1" : ProcessSnapshot | tokens : ("start_p1 (Event_1hsgsto)" T), subprocesses : (S), state : Running > => < "p1" : ProcessSnapshot | tokens : ("start_p1_end_p1 (Flow_1ttcsey)" T), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "two-incoming-message-flows-receive-task" : BPMNSystem | messages : (none), processes : (< "p2" : ProcessSnapshot | tokens : ("start_p2 (Event_1g2ic8d)"), subprocesses : (none), state : Running >
    < "p3" : ProcessSnapshot | tokens : ("start_p3 (Event_0bhy3w7)"), subprocesses : (none), state : Running >
    < "p1" : ProcessSnapshot | tokens : ("start_p1 (Event_1hsgsto)"), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-two-incoming-message-flows-receive-task .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet .
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

red modelCheck(init,  <> [] allTerminated) .
