load model-checker.maude .

--- Multiset implementation could be extracted as well.
fmod MSET is
    pr STRING .
    pr NAT .
    sorts NeMSet MSet .
    subsort String < NeMSet < MSet .

    op none : -> MSet [ctor] .
    op __ : MSet MSet -> MSet [ctor assoc comm id: none] .
    op __ : NeMSet MSet -> NeMSet [ctor ditto] .
    op __ : MSet NeMSet -> NeMSet [ctor ditto] .

    op contains : MSet String -> Bool .

    var X : String .
    var Y : String .
    var S S1 : MSet .

    eq contains(none, X) = false .
    eq contains(X S, X) = true .
    ceq contains(Y S, X) = contains(S, X) if X =/= Y .

    op size : MSet -> Nat .
    eq size(none) = 0 .
    eq size(X S) = size(S) + 1 .

    op lessOrEqualSize : MSet MSet -> Bool .
    ceq lessOrEqualSize(S, S1) = true if size(S) <= size(S1) .
    eq lessOrEqualSize(S, S1) = false [owise] .
endfm

mod BPMN-EXECUTION is
    pr MSET .
    pr STRING .
    pr CONFIGURATION .

    sort ProcessState .
    subsort String < Oid .

    --- BPMNSystem
    op BPMNSystem : -> Cid [ctor] .
    op messages :_ : MSet -> Attribute [ctor] .
    op processes :_ : Configuration -> Attribute [ctor] .

    --- Processes
    op ProcessSnapshot : -> Cid [ctor] .
    op tokens :_ : MSet -> Attribute [ctor] .
    op signals :_ : MSet -> Attribute [ctor] .
    op subprocesses :_ : Configuration -> Attribute [ctor] .
    ops Running, Terminated : -> ProcessState [ctor] .
    op state :_ : ProcessState -> Attribute [ctor] .

    --- Auxiliary
    op signalAll : Configuration MSet -> Configuration .
    op signal : MSet MSet -> MSet .
    op terminate : Configuration -> Configuration .

    vars P P1 : String .
    vars T T1 : MSet . --- tokens
    vars SIG : MSet . --- signals
    vars S : Configuration . --- subprocesses
    vars STATE : ProcessState . --- state
    var PS : Configuration .

    eq signalAll(none, T) = none .
    ceq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG signal(T, T1)), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) if lessOrEqualSize(SIG, T1). --- maximum signal bound is the number of tokens.
    eq signalAll(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS, T1) = < P : ProcessSnapshot | tokens : T, signals : (SIG), subprocesses : signalAll(S, T1), state : STATE > signalAll(PS, T1) [owise] .

    ceq signal(P T, T1) = (P + "_signal") signal(T, T1) if contains(T1, P) .
    eq signal(P T, T1) = signal(T, T1) [owise] .
    eq signal(none, T1) = none .

    eq terminate(none) = none .
    --- NOOP if already terminated
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated >) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Terminated > .
    --- Terminate all subprocesses recursively
    eq terminate(< P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : STATE > PS) = < P : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : terminate(S), state : Terminated > terminate(PS) .

    rl [naturalTerminate] :
    < P : ProcessSnapshot | tokens : none, signals : SIG, subprocesses : none, state : Running >
                            =>
    < P : ProcessSnapshot | tokens : none, signals : SIG, subprocesses : none, state : Terminated > .
endm

mod BPMN-EXECUTION-use-case-execution is
    pr BPMN-EXECUTION .

    --- Generated variables
    vars T T1 : MSet . --- tokens
    vars SIG SIG1 : MSet . --- signals
    vars M : MSet . --- messages
    vars S1 S S2 : Configuration . --- subprocesses
    vars P : Configuration . --- processes
    vars PS : Configuration . --- other processes

    --- Generated rules
    rl [Request_TL_status_Activity_1mxuhw3_start] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("Approaching_junction_Request_TL_status (Flow_1js6937)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_TL_status (Activity_1mxuhw3)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_TL_status_Activity_1mxuhw3_end] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_TL_status (Activity_1mxuhw3)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : ("Request_TL_status_TL_status_requested" M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_TL_status_RedOrGreen (Flow_0iyypf8)" T), signals : (none), subprocesses : (S), state : Running > P) > .
    rl [RedOrGreen_Gateway_06b4fdx] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_TL_status_RedOrGreen (Flow_0iyypf8)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("RedOrGreen (Gateway_06b4fdx)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e1_Gateway_0p8i4wr] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("B_is_green_e1 (Flow_0a915o2)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("e1_Pass_junction (Flow_1gxgvsb)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e1_Gateway_0p8i4wr] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("B_is_green_e1 (Flow_15jdo8x)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("e1_Pass_junction (Flow_1gxgvsb)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_green_TL_Activity_0mx96ar_start] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("B_is_red_Request_green_TL (Flow_0yvtjvt)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_green_TL (Activity_0mx96ar)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_green_TL_Activity_0mx96ar_end] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_green_TL (Activity_0mx96ar)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : ("Request_green_TL_B_green_requested_P2" M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_green_TL_B_is_green (Flow_1t1snu6)" T), signals : (none), subprocesses : (S), state : Running > P) > .
    rl [B_is_green_Event_0m8wala] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("Request_green_TL_B_is_green (Flow_1t1snu6)" T), signals : ("Request_green_TL_B_is_green (Flow_1t1snu6)_signal" SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("B_is_green_e1 (Flow_0a915o2)" T), signals : (SIG), subprocesses : (S), state : Running > .
    rl [B_is_red_Event_0ppvhy0] :  < "use-case-execution" : BPMNSystem | messages : ("A_and_C_green_B_red_Phase_1_B_is_red" M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("RedOrGreen (Gateway_06b4fdx)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("B_is_red_Request_green_TL (Flow_0yvtjvt)" T), signals : (SIG), subprocesses : (S), state : Running > P) > .
    rl [B_is_green_Event_0a8km7r] :  < "use-case-execution" : BPMNSystem | messages : ("A_and_C_red_B_green_Phase_2_B_is_green" M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("RedOrGreen (Gateway_06b4fdx)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("B_is_green_e1 (Flow_15jdo8x)" T), signals : (SIG), subprocesses : (S), state : Running > P) > .
    rl [Approaching_junction_Event_16ki5g9] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("Approaching_junction (Event_16ki5g9)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("Approaching_junction_Request_TL_status (Flow_1js6937)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Passed_junction_Event_115ty3b] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("Pass_junction_Passed_junction (Flow_0h5pioy)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [Pass_junction_Activity_0cdd7ru_start] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("e1_Pass_junction (Flow_1gxgvsb)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("Pass_junction (Activity_0cdd7ru)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Pass_junction_Activity_0cdd7ru_end] :  < "Bus controller (B)" : ProcessSnapshot | tokens : ("Pass_junction (Activity_0cdd7ru)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (B)" : ProcessSnapshot | tokens : ("Pass_junction_Passed_junction (Flow_0h5pioy)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e1_Gateway_0ys722g] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("e2_e1 (Flow_0r97aic)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("e1_Phase_1 (Flow_1ojaen0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e1_Gateway_0ys722g] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("Controller_started_e1 (Flow_1cnqphe)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("e1_Phase_1 (Flow_1ojaen0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Switch_to_P2_Activity_03yx3nw_Flow_048f6r1_start] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("P1_over_Switch_to_P2 (Flow_048f6r1)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P2 (Activity_03yx3nw)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Switch_to_P2_Activity_03yx3nw_Flow_1e2slwr_start] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("Phase_1_Switch_to_P2 (Flow_1e2slwr)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P2 (Activity_03yx3nw)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Switch_to_P2_Activity_03yx3nw_end] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P2 (Activity_03yx3nw)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P2_B_is_green_Phase_2 (Flow_1uxkn7t)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Switch_to_P1_Activity_1duk4ug_Flow_0tujs4p_start] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("P2_over_Switch_to_P1 (Flow_0tujs4p)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P1 (Activity_1duk4ug)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Switch_to_P1_Activity_1duk4ug_Flow_04ws78i_start] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("Phase_2_Switch_to_P1 (Flow_04ws78i)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P1 (Activity_1duk4ug)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Switch_to_P1_Activity_1duk4ug_end] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P1 (Activity_1duk4ug)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P1_A_&_C_are_green_Phase_1 (Flow_1xv5lrj)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [B_is_green_Phase_2_Event_1w3al4m] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P2_B_is_green_Phase_2 (Flow_1uxkn7t)" T), signals : (SIG), subprocesses : (S), state : Running > PS) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (signalAll(< "T-Junction controller" : ProcessSnapshot | tokens : ("B_is_green_Phase_2_Phase_2 (Flow_11hp3v6)" T), signals : (SIG), subprocesses : (S), state : Running > PS, "Request_green_TL_B_is_green (Flow_1t1snu6)")) > .
    rl [A_&_C_are_green_Phase_1_Event_18ivrke] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : ("Switch_to_P1_A_&_C_are_green_Phase_1 (Flow_1xv5lrj)" T), signals : (SIG), subprocesses : (S), state : Running > PS) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (signalAll(< "T-Junction controller" : ProcessSnapshot | tokens : ("A_&_C_are_green_Phase_1_e2 (Flow_0o0zql1)" T), signals : (SIG), subprocesses : (S), state : Running > PS, "Request_green_TL_A_is_green (Flow_06b0un1)")) > .
    rl [Controller_started_Event_0e1tcn5] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("Controller_started (Event_0e1tcn5)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Controller_started_e1 (Flow_1cnqphe)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e2_Gateway_1xtvabb] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("A_&_C_are_green_Phase_1_e2 (Flow_0o0zql1)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("e2_e1 (Flow_0r97aic)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e2_Gateway_1xtvabb] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("A_&_C_are_green_Phase_1_e2 (Flow_0o0zql1)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("stop (Flow_14jo1v0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Phase_2_Activity_14ojnon_start] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("B_is_green_Phase_2_Phase_2 (Flow_11hp3v6)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("Event_15urqhf (Event_15urqhf)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Phase_2_Activity_14ojnon_end] :  < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : (none), signals : (SIG), subprocesses : (none), state : Terminated > S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Phase_2_Switch_to_P1 (Flow_04ws78i)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Gateway_0ue58r0_Gateway_0ue58r0_Flow_0jrj68j] :  < "Phase_2" : ProcessSnapshot | tokens : ("Event_15urqhf_Gateway_0ue58r0 (Flow_0jrj68j)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_2" : ProcessSnapshot | tokens : ("Gateway_0ue58r0 (Gateway_0ue58r0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Gateway_0ue58r0_Gateway_0ue58r0_Flow_1ogjgsu] :  < "Phase_2" : ProcessSnapshot | tokens : ("A_and_C_red_B_green_Phase_2_Gateway_0ue58r0 (Flow_1ogjgsu)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_2" : ProcessSnapshot | tokens : ("Gateway_0ue58r0 (Gateway_0ue58r0)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Event_15urqhf_Event_15urqhf] :  < "Phase_2" : ProcessSnapshot | tokens : ("Event_15urqhf (Event_15urqhf)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_2" : ProcessSnapshot | tokens : ("Event_15urqhf_Gateway_0ue58r0 (Flow_0jrj68j)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [TL_status_requested_Event_1aakyu0] :  < "use-case-execution" : BPMNSystem | messages : ("Request_TL_status_TL_status_requested" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("Gateway_0ue58r0 (Gateway_0ue58r0)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("TL_status_requested_A_and_C_red_B_green_Phase_2 (Flow_0gli7zn)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [TL_status_requested_Event_1aakyu0] :  < "use-case-execution" : BPMNSystem | messages : ("Request_TL_status_TL_status_requested" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("Gateway_0ue58r0 (Gateway_0ue58r0)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("TL_status_requested_A_and_C_red_B_green_Phase_2 (Flow_0gli7zn)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [A_and_C_red_B_green_Phase_2_Event_1bkpsx5] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("TL_status_requested_A_and_C_red_B_green_Phase_2 (Flow_0gli7zn)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : ("A_and_C_red_B_green_Phase_2_B_is_green" "A_and_C_red_B_green_Phase_2_A_is_red" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("A_and_C_red_B_green_Phase_2_Gateway_0ue58r0 (Flow_1ogjgsu)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [A_or_C_green_requested_P2_Event_1iv9kfs] :  < "use-case-execution" : BPMNSystem | messages : ("Request_green_TL_A_or_C_green_requested_P2" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("Gateway_0ue58r0 (Gateway_0ue58r0)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : ("A_or_C_green_requested_P2_Event_1k7ycdb (Flow_0h09fpo)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [Event_1k7ycdb_Event_1k7ycdb] :  < "Phase_2" : ProcessSnapshot | tokens : ("A_or_C_green_requested_P2_Event_1k7ycdb (Flow_0h09fpo)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_2" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [P2_over_Event_0rzfk86] :  < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Phase_2" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (S1), state : Running > S2), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("P2_over_Switch_to_P1 (Flow_0tujs4p)" T), signals : (none), subprocesses : (S2), state : Running > .
    rl [Phase_1_Activity_0rr1q4o_start] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("e1_Phase_1 (Flow_1ojaen0)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("Event_0xewq6z (Event_0xewq6z)"), signals : (none), subprocesses : (none), state : Running > S), state : Running > .
    rl [Phase_1_Activity_0rr1q4o_end] :  < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : (none), signals : (SIG), subprocesses : (none), state : Terminated > S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("Phase_1_Switch_to_P2 (Flow_1e2slwr)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Event_0xewq6z_Event_0xewq6z] :  < "Phase_1" : ProcessSnapshot | tokens : ("Event_0xewq6z (Event_0xewq6z)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_1" : ProcessSnapshot | tokens : ("Event_0xewq6z_Gateway_1kmngej (Flow_1s1aaak)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Gateway_1kmngej_Gateway_1kmngej_Flow_1s1aaak] :  < "Phase_1" : ProcessSnapshot | tokens : ("Event_0xewq6z_Gateway_1kmngej (Flow_1s1aaak)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_1" : ProcessSnapshot | tokens : ("Gateway_1kmngej (Gateway_1kmngej)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Gateway_1kmngej_Gateway_1kmngej_Flow_02nehb8] :  < "Phase_1" : ProcessSnapshot | tokens : ("A_and_C_green_B_red_Phase_1_Gateway_1kmngej (Flow_02nehb8)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_1" : ProcessSnapshot | tokens : ("Gateway_1kmngej (Gateway_1kmngej)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [TL_status_requested_Event_1cy5x4c] :  < "use-case-execution" : BPMNSystem | messages : ("Request_TL_status_TL_status_requested" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("Gateway_1kmngej (Gateway_1kmngej)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("TL_status_requested_A_and_C_green_B_red_Phase_1 (Flow_1eqsy0f)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [TL_status_requested_Event_1cy5x4c] :  < "use-case-execution" : BPMNSystem | messages : ("Request_TL_status_TL_status_requested" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("Gateway_1kmngej (Gateway_1kmngej)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("TL_status_requested_A_and_C_green_B_red_Phase_1 (Flow_1eqsy0f)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [A_and_C_green_B_red_Phase_1_Event_068kiho] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("TL_status_requested_A_and_C_green_B_red_Phase_1 (Flow_1eqsy0f)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : ("A_and_C_green_B_red_Phase_1_B_is_red" "A_and_C_green_B_red_Phase_1_A_is_green" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("A_and_C_green_B_red_Phase_1_Gateway_1kmngej (Flow_02nehb8)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [B_green_requested_P2_Event_029k7yc] :  < "use-case-execution" : BPMNSystem | messages : ("Request_green_TL_B_green_requested_P2" M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("Gateway_1kmngej (Gateway_1kmngej)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "T-Junction controller" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : ("B_green_requested_P2_Event_1wd4tix (Flow_0qjexh0)" T), signals : (SIG), subprocesses : (S), state : Running > S1), state : Running > P) > .
    rl [Event_1wd4tix_Event_1wd4tix] :  < "Phase_1" : ProcessSnapshot | tokens : ("B_green_requested_P2_Event_1wd4tix (Flow_0qjexh0)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Phase_1" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [P1_over_Event_0njchvs] :  < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (SIG), subprocesses : (< "Phase_1" : ProcessSnapshot | tokens : (T1), signals : (SIG1), subprocesses : (S1), state : Running > S2), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : ("P1_over_Switch_to_P2 (Flow_048f6r1)" T), signals : (none), subprocesses : (S2), state : Running > .
    rl [Controller_stopped_Event_1dpui4t] :  < "T-Junction controller" : ProcessSnapshot | tokens : ("stop (Flow_14jo1v0)" T), signals : (SIG), subprocesses : (S), state : Running > => < "T-Junction controller" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_TL_status_Activity_08rkpnz_start] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("Approaching_junction_Request_TL_status (Flow_004br76)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_TL_status (Activity_08rkpnz)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_TL_status_Activity_08rkpnz_end] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_TL_status (Activity_08rkpnz)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : ("Request_TL_status_TL_status_requested" M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_TL_status_RedOrGreen (Flow_00ahncj)" T), signals : (none), subprocesses : (S), state : Running > P) > .
    rl [RedOrGreen_Gateway_14h9lg3] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_TL_status_RedOrGreen (Flow_00ahncj)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("RedOrGreen (Gateway_14h9lg3)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e1_Gateway_06qfoa5] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("A_is_green_e1 (Flow_1io4vwq)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("e1_Pass_junction (Flow_0c3nyvf)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [e1_Gateway_06qfoa5] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("A_is_green_e1 (Flow_0junba2)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("e1_Pass_junction (Flow_0c3nyvf)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_green_TL_Activity_0bc0drd_start] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("A_is_red_Request_green_TL (Flow_0ded6yp)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_green_TL (Activity_0bc0drd)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Request_green_TL_Activity_0bc0drd_end] :  < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_green_TL (Activity_0bc0drd)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : ("Request_green_TL_A_or_C_green_requested_P2" M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_green_TL_A_is_green (Flow_06b0un1)" T), signals : (none), subprocesses : (S), state : Running > P) > .
    rl [A_is_green_Event_13r0b7u] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("Request_green_TL_A_is_green (Flow_06b0un1)" T), signals : ("Request_green_TL_A_is_green (Flow_06b0un1)_signal" SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("A_is_green_e1 (Flow_0junba2)" T), signals : (SIG), subprocesses : (S), state : Running > .
    rl [A_is_red_Event_0ecq97l] :  < "use-case-execution" : BPMNSystem | messages : ("A_and_C_red_B_green_Phase_2_A_is_red" M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("RedOrGreen (Gateway_14h9lg3)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("A_is_red_Request_green_TL (Flow_0ded6yp)" T), signals : (SIG), subprocesses : (S), state : Running > P) > .
    rl [A_is_green_Event_1wnzb35] :  < "use-case-execution" : BPMNSystem | messages : ("A_and_C_green_B_red_Phase_1_A_is_green" M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("RedOrGreen (Gateway_14h9lg3)" T), signals : (SIG), subprocesses : (S), state : Running > P) > => < "use-case-execution" : BPMNSystem | messages : (M), processes : (< "Bus controller (A)" : ProcessSnapshot | tokens : ("A_is_green_e1 (Flow_1io4vwq)" T), signals : (SIG), subprocesses : (S), state : Running > P) > .
    rl [Approaching_junction_Event_0xodosv] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("Approaching_junction (Event_0xodosv)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("Approaching_junction_Request_TL_status (Flow_004br76)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Passed_junction_Event_0bgms6k] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("Pass_junction_Passed_junction (Flow_0r8tgda)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : (T), signals : (none), subprocesses : (S), state : Running > .
    rl [Pass_junction_Activity_1tchett_start] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("e1_Pass_junction (Flow_0c3nyvf)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("Pass_junction (Activity_1tchett)" T), signals : (none), subprocesses : (S), state : Running > .
    rl [Pass_junction_Activity_1tchett_end] :  < "Bus controller (A)" : ProcessSnapshot | tokens : ("Pass_junction (Activity_1tchett)" T), signals : (SIG), subprocesses : (S), state : Running > => < "Bus controller (A)" : ProcessSnapshot | tokens : ("Pass_junction_Passed_junction (Flow_0r8tgda)" T), signals : (none), subprocesses : (S), state : Running > .

    --- Start configuration which would be generated
    op init : -> Configuration .
    eq init = < "use-case-execution" : BPMNSystem | messages : (none), processes : (< "Bus controller (B)" : ProcessSnapshot | tokens : ("Approaching_junction (Event_16ki5g9)"), signals : (none), subprocesses : (none), state : Running >
    < "T-Junction controller" : ProcessSnapshot | tokens : ("Controller_started (Event_0e1tcn5)"), signals : (none), subprocesses : (none), state : Running >
    < "Bus controller (A)" : ProcessSnapshot | tokens : ("Approaching_junction (Event_0xodosv)"), signals : (none), subprocesses : (none), state : Running >) > .
endm

mod BPMN-PREDS is
    pr BPMN-EXECUTION-use-case-execution .
    pr SATISFACTION .
    subsort Configuration < State .

    var C : Configuration .
    var P : Prop .
    var X Y : Oid .
    var T : MSet . --- tokens
    var SIG : MSet . --- signals
    var M : MSet . --- messages
    var T1 : NeMSet .
    var S : Configuration .
    var State : ProcessState .


    op allTerminated : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : T, signals : SIG, subprocesses : S, state : Running > C) > |= allTerminated = false .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= allTerminated = true [owise] .

    op unsafe : -> Prop .
    eq < X : BPMNSystem | messages : M, processes : (< Y : ProcessSnapshot | tokens : (T1 T1 T), signals : SIG, subprocesses : S, state : State > C) > |= unsafe = true .
    eq < X : BPMNSystem | messages : M, processes : (C) > |= unsafe = false [owise] .

    --- Generated atomic propositions
    --- no propositions
endm

mod BPMN-CHECK is
    pr BPMN-PREDS .
    pr MODEL-CHECKER .
    pr LTL-SIMPLIFIER .

    var X : Configuration .
endm

search init =>! X such that X |= allTerminated = true .
