name: Build & Push to Azure and Dockerhub

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./server/gradlew
      - name: Build Jar
        run: ./server/gradlew bootJar
      - name: Build docker image
        run: docker build -t tg2022.azurecr.io/bpmnanalyzer:v1 .

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      - name: Push to Azure
        run: docker push tg2022.azurecr.io/bpmnanalyzer:v1

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag image
        run: docker tag tg2022.azurecr.io/rust_bpmn_analyzer:v1 tkra/bpmn-analyzer
      - name: Push to Dockerhub
        run: docker push tkra/bpmn-analyzer