name: Build, Push & Deploy to Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
          cache: "gradle"
      - name: Build Jar
        run: ./gradlew bootJar
        working-directory: server
      - name: Build docker image
        run: |
          docker build -t tkra/bpmn-analyzer:latest -t tkra/bpmn-analyzer:${{ github.sha }} .
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Dockerhub
        run: |
          docker push tkra/bpmn-analyzer:latest
          docker push tkra/bpmn-analyzer:${{ github.sha }}
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: Tim
          containerAppName: bpmn-analyzer
          imageToDeploy: docker.io/tkra/bpmn-analyzer:${{ github.sha }}
