name: Analyze ui
on:
  push:
    paths:
      - "generation-ui/**"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  prettier:
    name: Prettier check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generation-ui
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./generation-ui/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Prettier check
        run: npm run check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generation-ui
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./generation-ui/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: generation-ui/coverage/generation-ui/lcov.info

  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.0-noble
    defaults:
      run:
        working-directory: ./generation-ui
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        run: npm run e2e
        env:
          HOME: /root
      - name: Upload Playwright report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: generation-ui/playwright-report/
          retention-days: 30

  sonarcloud:
    name: Analyze ui
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download coverage report
        uses: actions/download-artifact@v8
        with:
          name: coverage-report
          path: generation-ui/coverage/generation-ui
      - name: SonarCloud Scan
        continue-on-error: true
        uses: SonarSource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./generation-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
